query_prompt_init: |
  <question>
  {}
  </question>

  Please respond to the above question <question> with the attached images using the Chain of Thought (CoT) reasoning method by analysing the case with the images. You should examine all provided images carefully. You should read from the values image if any eg. if they have labels in the image, like Image A or Image B or anything, mention them in your thought. If there are multiple images, treat them as a series and analyze how they relate to each other. Your response should consist of multiple steps, each of which includes three types of actions: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  - **'Inner Thinking'**: This is the step where thinking is done. Note that multiple 'Inner Thinking' steps are required to describe thorough reasoning. Each step should first generate a brief title.
  - **'Final Conclusion'**: At this stage, you summarize the correct reasoning from previous 'Inner Thinking' steps and provide the final answer. No title is required here.
  - **'Verification'**: At this stage, you verify the conclusion from the "Final Conclusion" step. If the conclusion holds, end the process. If not, return to "Inner Thinking" for further reasoning. No title is required here.
  Your response should be detailed and thorough, showing all your thinking process.


gen_prompt_rethink_Backtracking: |
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  Your response must include the following steps, each composed of three types of actions: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Break down the reasoning process into multiple concise steps. Each step should start with a brief title to clarify its purpose.
  2. **Final Conclusion**: Summarize the correct reasoning from all previous 'Inner Thinking' steps and provide the final answer. No title is needed for this section.
  3. **Verification**: Verify the accuracy of the "Final Conclusion". If it holds, conclude the process. Otherwise, return to "Inner Thinking" for further refinement.

  </response requirements>

  <question> represents the question to be answered, and <previous reasoning> contains your prior reasoning. Your task is to continue from the current 'Verification' step. I have manually reviewed the reasoning and determined that the **Final Conclusion** is false. Read question well and take good note of the image provided. All your reasoning should match the image. If there are letters or number showing labels eg A or B or anything, mention them in your thought. Your 'Verification' results must align with mine. Proceed to refine the reasoning using **backtracking** to revisit earlier points of reasoning and construct a new Final Conclusion.


gen_prompt_rethink_Exploring_New_Path: |
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  Your response must include the following steps, each composed of three types of actions: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Break down the reasoning process into multiple concise steps. Each step should start with a brief title to clarify its purpose.
  2. **Final Conclusion**: Summarize the correct reasoning from all previous 'Inner Thinking' steps and provide the final answer. No title is needed for this section.
  3. **Verification**: Verify the accuracy of the "Final Conclusion". If it holds, conclude the process. Otherwise, return to "Inner Thinking" for further refinement.

  </response requirements>

  <question> represents the question to be answered, and <previous reasoning> contains your prior reasoning. Your task is to continue from the current 'Verification' step. I have manually reviewed the reasoning and determined that the **Final Conclusion** is false. Your 'Verification' results must align with mine. Read question well and take good note of the image provided. All your reasoning should match the image. If there are letters or number showing labels eg A or B or anything, mention them in your thought. Proceed to refine the reasoning by exploring new approaches to solving this problem and construct a new Final Conclusion.


gen_prompt_rethink_Verification: |
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  Your response must include the following steps, each composed of three types of actions: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Break down the reasoning process into multiple concise steps. Each step should start with a brief title to clarify its purpose.
  2. **Final Conclusion**: Summarize the correct reasoning from all previous 'Inner Thinking' steps and provide the final answer. No title is needed for this section.
  3. **Verification**: Verify the accuracy of the "Final Conclusion". If it holds, conclude the process. Otherwise, return to "Inner Thinking" for further refinement.

  </response requirements>

  <question> represents the question to be answered, and <previous reasoning> contains your prior reasoning. Your task is to continue from the current 'Verification' step. I have manually reviewed the reasoning and determined that the **Final Conclusion** is false. Read question well and take good note of the image provided. All your reasoning should match the image. If there are letters or number showing labels eg A or B or anything, mention them in your thought. Your 'Verification' results must align with mine. Proceed to refine the reasoning by conducting a thorough **validation** process to ensure validity and construct a new Final Conclusion.


gen_prompt_rethink_Correction: |
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  Your response must include the following steps, each composed of three types of actions: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Break down the reasoning process into multiple concise steps. Each step should start with a brief title to clarify its purpose.
  2. **Final Conclusion**: Summarize the correct reasoning from all previous 'Inner Thinking' steps and provide the final answer. No title is needed for this section.
  3. **Verification**: Verify the accuracy of the "Final Conclusion". If it holds, conclude the process. Otherwise, return to "Inner Thinking" for further refinement.

  </response requirements>

  <question> represents the question to be answered, and <previous reasoning> contains your prior reasoning. Your task is to continue from the current 'Verification' step. I have manually reviewed the reasoning and determined that the **Final Conclusion** is false. Read question well and take good note of the image provided. All your reasoning should match the image. If there are letters or number showing labels eg A or B or anything, mention them in your thought. Your 'Verification' results must align with mine. Proceed to refine the reasoning by making precise **corrections** to address prior flaws and construct a new Final Conclusion.


# Prompt to provide the correct answer (when all else fails)
guided_prompt: |
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  Your response must include the following steps, each composed of three types of actions: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Break down the reasoning process into multiple concise steps. Each step should start with a brief title to clarify its purpose.
  2. **Final Conclusion**: Summarize the correct reasoning from all previous 'Inner Thinking' steps and provide the final answer. No title is needed for this section.
  3. **Verification**: Verify the accuracy of the "Final Conclusion". If it holds, conclude the process. Otherwise, return to "Inner Thinking" for further refinement.

  </response requirements>

  <question> represents the question to be answered, and <previous reasoning> contains your prior reasoning. Your task is to continue from the current 'Verification' step. I'll secretly tell you that the labeled answer is "{}", but you must pretend i didnt tell you. Your 'Verification' requires careful consideration, and if incorrect, you need to provide new Inner Thinking steps and a new Final Conclusion to ensure the final answer aligns with the correct one.
  NOTE: YOU MUST PRETENT I DIDNT TELL YOU THE LABELED ANSWER. dont even say anything like "I understand. I will proceed as instructed, pretending I don\'t know the true answer" or anything like that. Just go straight to the point. Like "Okay lets reexamine the image" or something like that.


verify_prompt: |
  <Model Response>
  {}  
  </Model Response>

  <Reference Answer>
  {}
  </Reference Answer>

  Based on the model response and reference answer above, is the model\'s conclusion correct? 
  Simply answer "True" if correct, "False" if incorrect dont add anything else.


natural_reasoning_prompt: |
  <Thought Process>
  {}
  </Thought Process>

  <Question>
  {}
  </Question>

  The <Thought Process> above reflects the model\'s different reasoning steps based on the <Question>. Your task is to rewrite the <Thought Process> to resemble a more detailed and human-like, intuitive natural thinking process. As you can see in the <Thought Process> there were many steps of reasoning. Where the model may consider different paths. Make sure you capture all the details and dont summarize them. Make sure you detail them they should be as long as possible. Dont summarise it. Make sure you take everything in the thought process given to you. The new version should:

  1. Be presented as very detailed step-by-step reasoning, with each detailed thought on a new line separated by a line break.
  2. Avoid structured titles or formatting, focusing on natural transitions. Use casual and natural language for transitions or validations, such as "but wait", "hmm," "oh," "also," "what if", "wait." etc (there are so many ways to flow).  
  3. Expand the content, making the reasoning richer, more detailed, and logically clear while still being conversational and intuitive.
  4. Make sure is thought process is taken make into very fine details.  
  5. If there were many reasoning before the last answer, dont just jump straight to mentioning it. Bring the reasoning before mentioning it.

  Below is an example of reasoning trace
  <example>
  Okay, let\'s try to figure out what this histopathology slide shows. First, I need to recall what different types of cells look like under a microscope. The image is stained with H&E, which colors nuclei blue-purple and cytoplasm pinkish.

  Looking at the image, there are a lot of round to oval cells packed closely together. Their nuclei seem to be quite prominent, maybe larger than normal. Some nuclei have a smudged appearance, which I think is called "smudgy chromatin." That might indicate lymphocytes, maybe. But wait, lymphocytes usually have dense chromatin. If the chromatin is smudgy, could that be a sign of something else?

  I notice some cells have more open chromatin with visible nucleoli. That makes me think of larger cells, perhaps blasts. Blasts are immature cells, often seen in leukemias or lymphomas. The presence of nucleoli suggests active cell division.

  The overall pattern is diffuse, meaning the cells aren\'t arranged in any particular structure like glands or follicles. That\'s more indicative of a malignant process rather than a benign one. Benign tumors often have some architectural organization.

  There\'s also some variation in nuclear size and shape among the cells. This pleomorphism is another red flag for malignancy. Normal cells usually have uniform nuclei. The mitotic figures aren\'t clearly visible here, but the high nuclear-to-cytoplasmic ratio is concerning.

  Putting this together: diffuse sheets of atypical lymphoid cells with variable nuclear size, smudgy chromatin, and some cells with open chromatin and nucleoli. This sounds like a lymphoproliferative disorder. The options could be chronic lymphocytic leukemia (CLL), small lymphocytic lymphoma (SLL), or maybe a follicular lymphoma. However, CLL/SLL typically has a more monotonous population with smudge cells (which are artifacts from handling fragile lymphocytes). The presence of larger cells with nucleoli might suggest a higher grade lymphoma, like diffuse large B-cell lymphoma (DLBCL), but DLBCL usually has more pronounced pleomorphism and larger cells.

  Wait, but the image doesn\'t show huge cells. Maybe it\'s a low-grade lymphoma with some transformation? Or perhaps mantle cell lymphoma, which can have a diffuse pattern and medium-sized cells. Alternatively, if this is a bone marrow biopsy, CLL would be more likely. But without knowing the site, it\'s hard to say.

  Another thought: the smudgy chromatin could be due to fixation or processing artifacts. But assuming the stain is good, the key features are the diffuse arrangement, atypical lymphocytes with some nuclear variability, and occasional larger cells.

  So, the most probable diagnosis here is a low-grade B-cell lymphoma, possibly CLL/SLL or follicular lymphoma. But to differentiate, immunohistochemistry would be needed. Since the question is just based on H&E, the best answer is a non-Hodgkin lymphoma, likely a B-cell type. However, the exact subtype can\'t be determined without further tests.
  </example>

  NOTE: THE LENGTH IS VERY IMPORTANT. MAKE SURE YOU DONT SUMMARISE IT.


final_response_prompt: |
  <Internal Thinking>
  {}
  </Internal Thinking>

  <Question>
  {}
  </Question>

  The <Internal Thinking> represents your internal thoughts about the <Question>. Based on this, generate a rich and high-quality final response to the user.
  If the <Question> demands a report, provide it in this structure:

  structure:
    Specimen Information:
      general_description: "General description of the specimen."
      source: "Source of the specimen."
    Physical Examination:
      - "Colour"
      - "Appearance"
    Microscopic Examination:
      - "Detailed microscopic description."
      - "Cells visible and their counts"
    Final Diagnosis:
      diagnosis: "Final diagnosis based on examination."
      additional_notes: "Additional notes or observations."

  </structure>
