# Handwriting OCR Pipeline Configuration
# Focused on text recognition accuracy, not Q&A reasoning

# Data paths (relative to project root)
images_dir: "src/data/i_am_handwriting/cropped_handwritten"
xml_dir: "src/data/i_am_handwriting/xml"

# API Configuration
model_name: "google/gemini-2.0-flash-001"
api_url: "https://openrouter.ai/api/v1"

# Processing Configuration
start_index: 0  # Start index for processing images
max_search_attempts: 3  # Maximum attempts for OCR processing
max_search_depth: 2  # Maximum depth for search in OCR processing
efficient_search: true  # Use efficient search strategies
num_processes: 2
batch_size: 20
limit_num: null  # null for all images, or set a number for testing

# OCR Evaluation Settings
calculate_metrics: true
save_detailed_results: true
include_error_analysis: true

# Output Configuration
results_dir: "data/i_am_handwriting/reasoning_samples"
logs_dir: "logs/handwriting_ocr"
