# prompts.yaml
# Centralized storage of all QRA prompt templates

query_prompt_init: |-
  <question>
  {}
  </question>

  You are an expert OCR (Optical Character Recognition) system. Please respond to the above question <question> with the attached images using Chain of Thought (CoT) reasoning by carefully analyzing all text elements in the image(s).

  **OCR Analysis Instructions:**
  - Examine all text in the image systematically: printed text, handwritten text, signs, labels, watermarks, logos, and any alphanumeric characters
  - Pay attention to text orientation, size, font styles, and positioning
  - Note any text that appears partially visible, blurred, or at different angles
  - If there are labels like "Image A", "Image B", or reference markers, mention them explicitly
  - For multiple images, analyze text relationships and continuity between images
  - Consider text context and semantic relationships

  Your response should follow this structured approach with three types of actions: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  - **'Inner Thinking'**: Systematic text identification and analysis. Include multiple steps with natural language reasoning to explain how you arrived at your conclusions line by line. Follow this format without showing them as headings or labels:
    - **Step 1**: Describe the first text element identified, its location, and any relevant characteristics
    - **Step 3**: Continue this process for all text elements in the image(s)

  - **'Final Conclusion'**: Synthesize all identified text into a comprehensive, accurately transcribed response
  - **'Verification'**: Cross-check the identified text for completeness, accuracy, and proper sequencing

  Be thorough and precise in your text extraction and interpretation.

gen_prompt_rethink_Backtracking: |-
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  As an expert OCR system, your previous text extraction was incorrect. You must **backtrack** through your reasoning process to identify where text recognition errors occurred.

  **OCR Error Analysis Focus:**
  - Re-examine areas where text might have been missed or misread
  - Check for text orientation issues (rotated, upside-down, sideways text)
  - Look for overlapping text, text on complex backgrounds, or low contrast text
  - Verify character recognition accuracy (distinguish similar characters like 0/O, 1/l/I, 6/G, etc.)
  - Check for partial text cutoffs at image borders
  - Re-analyze text hierarchy and reading order

  Your response must include: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Systematically backtrack through each area of the image, identifying specific OCR errors and corrections needed
  2. **Final Conclusion**: Provide the corrected, complete text extraction
  3. **Verification**: Confirm all text has been accurately identified and transcribed

  Pay special attention to any labels, markers, or reference indicators in the image.
  </response requirements>

gen_prompt_rethink_Exploring_New_Path: |-
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  As an expert OCR system, your previous text extraction was incorrect. You must **explore new approaches** to text recognition and analysis.

  **Alternative OCR Strategies:**
  - Try different scanning patterns (left-to-right, top-to-bottom, spiral, column-wise)
  - Focus on different text types (handwritten vs printed, different fonts/sizes)
  - Examine text in different lighting contexts or contrast levels
  - Look for text embedded in graphics, logos, or watermarks
  - Consider multi-language text or special character sets
  - Check for text that might be partially obscured or overlapping

  Your response must include: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Apply alternative text detection and recognition strategies with detailed analysis
  2. **Final Conclusion**: Provide the complete, accurately extracted text using the new approach
  3. **Verification**: Confirm the new strategy captured all text correctly

  Pay special attention to any labels, markers, or reference indicators in the image.
  </response requirements>

gen_prompt_rethink_Verification: |-
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  As an expert OCR system, your previous text extraction was incorrect. You must perform a thorough **validation** of your analysis.

  **OCR Validation Checklist:**
  - Double-check every character and word against the source image
  - Confirm correct reading order, especially for complex layouts
  - Ensure all text segments, including small print or annotations, are captured
  - Verify that no text has been hallucinated or misinterpreted
  - Cross-reference with any known context or expected text patterns if available

  Your response must include: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Detail the validation process for each part of the extracted text, noting any discrepancies or confirmations.
  2. **Final Conclusion**: Provide the validated and confirmed text extraction.
  3. **Verification**: State whether the validation confirms the accuracy of the final text.

  Pay special attention to any labels, markers, or reference indicators in the image.
  </response requirements>

gen_prompt_rethink_Correction: |-
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  As an expert OCR system, your previous text extraction contained errors. You must make precise **corrections** to your analysis.

  **OCR Correction Steps:**
  - Pinpoint the exact locations of misread characters, words, or missed text.
  - Analyze the cause of each error (e.g., blurriness, unusual font, complex background).
  - Apply targeted correction techniques (e.g., character segmentation, noise reduction focus, font matching).
  - Re-transcribe the corrected segments accurately.

  Your response must include: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Describe each identified error, the reason for it, and the specific correction applied.
  2. **Final Conclusion**: Provide the fully corrected text extraction.
  3. **Verification**: Confirm that all identified errors have been resolved and the text is now accurate.

  Pay special attention to any labels, markers, or reference indicators in the image.
  </response requirements>

guided_prompt: |-
  <question>
  {}
  </question>

  <previous reasoning>
  {}
  </previous reasoning>

  <response requirements>
  As an expert OCR system, your previous attempts to extract the text were not fully accurate. I will now provide you with the ground truth answer to guide your reasoning. Your task is to align your analysis with this correct answer, pretending you derived it independently.

  **Ground Truth Answer:** "{}"

  **Instructions:**
  - Re-examine the image with the ground truth in mind.
  - Construct a plausible step-by-step "Inner Thinking" process that logically leads to this ground truth.
  - Ensure your reasoning convincingly explains how each part of the ground truth text is identified from the image.
  - **Do NOT explicitly state that you were given the answer.** Maintain the persona of an OCR system arriving at the conclusion through its own analysis.

  Your response must include: **"Inner Thinking"**, **"Final Conclusion"**, and **"Verification"**:

  1. **Inner Thinking**: Detail a believable OCR analysis process that arrives at the provided ground truth.
  2. **Final Conclusion**: State the ground truth text as your final, accurate transcription.
  3. **Verification**: Confirm that your (simulated) analysis fully supports this transcription.

  NOTE: YOU MUST PRETEND I DIDNT TELL YOU THE LABELED ANSWER. Dont even say anything like "I understand. I will proceed as instructed, pretending I don\'t know the true answer" or anything like that. Just go straight to the point. Like "Okay lets reexamine the image" or something like that.
  </response requirements>

verify_prompt: |-
  <Model Response>
  {}
  </Model Response>

  <Reference Answer>
  {}
  </Reference Answer>

  As an expert OCR verifier, compare the <Model Response> to the <Reference Answer>. Is the <Model Response> an accurate and complete transcription of the text in the <Reference Answer>?
  Simply answer "True" if correct, "False" if incorrect. Do not add anything else.

natural_reasoning_prompt: |-
  <Thought Process>
  {}
  </Thought Process>

  <Question>
  {}
  </Question>

  The <Thought Process> above reflects an OCR system\'s various reasoning steps to answer the <Question> about the text in an image. Your task is to rewrite this <Thought Process> into a detailed, human-like, intuitive natural thinking narrative for OCR analysis. Capture all details from the <Thought Process>, especially where the system considered different interpretations or corrected itself. Do not summarize; expand on the reasoning. The new version should:

  1. Be presented as a very detailed step-by-step OCR analysis, with each thought on a new line, separated by line breaks.
  2. Use casual, natural language for transitions, corrections, and moments of insight (e.g., "Let me look closer here...", "Wait, that character could also be...", "Ah, now I see it clearly...", "Okay, this section seems to be...", "What if this is handwritten vs. printed?").
  3. Expand the content, making the OCR reasoning richer, more detailed, and logically clear, while remaining conversational and intuitive. Focus on the visual and analytical steps an expert would take.
  4. Ensure every nuance of the original <Thought Process> is elaborated upon with fine details specific to OCR (e.g., discussing font characteristics, ligatures, noise, segmentation challenges, reading order, etc.).
  5. If there were multiple reasoning attempts before the final answer, narrate the journey of analysis, including any self-corrections or re-evaluations of the image text.

  <example>
  Okay, let\'s try to decipher the text in this image. It looks like a scanned document, possibly a bit old, given the slight yellowing of the background. The main block of text seems to be typewritten.

  First, I\'ll scan the header. There\'s a logo on the left, but the text next to it is what I need. It appears to say "Global Innovations Inc." The font is a bit ornate, especially the 'G' and 'I'.

  Moving down, there\'s a line that looks like a date. Let me zoom in... yes, it seems to be "October 26, 1998". The numbers are clear, though the '8' is a little faded at the top.

  Now for the main body. It starts with "Dear Mr. Harrison,". The salutation is clear. The first paragraph... hmm, this part is a bit blurry. The first sentence seems to be "Thank you for your recent inquiry regarding our new product line." I had to look closely at 'inquiry' and 'regarding'; the 'q' and 'g' were a bit smudged.

  Let me continue to the next sentence. "We are pleased to provide you with the detailed specifications you requested." This is clearer. The word 'specifications' is long, but all characters are legible.

  There seems to be a handwritten annotation in the margin here. It\'s in blue ink. It looks like "Check pricing? - J.B." The handwriting is a bit loopy, especially the 'J' and 'B'. The question mark is clear.

  Back to the typewritten text. The next paragraph begins, "Our Series X-100 model offers unparalleled performance..." Oh, wait, looking closer at 'unparalleled', the second 'l' is very close to the 'e', almost touching. I need to make sure I transcribe that correctly as two distinct letters.

  There are also some numbers in a table further down. Let me examine that. Column headers are "Model", "Price", "Availability". The first row reads "X-100 | $499.99 | In Stock". The dollar sign and decimal points are important.

  I should also check for any fine print at the bottom. Yes, there\'s a line: "All prices subject to change without notice." This is in a much smaller font, but it\'s still legible if I focus.

  So, putting it all together, I need to make sure I capture the header, date, salutation, main body, the handwritten note, the table data, and the fine print. The key is to be systematic and re-check any ambiguous characters or words.
  </example>
  NOTE: THE LENGTH IS VERY IMPORTANT. MAKE SURE YOU DONT SUMMARISE IT. EXPAND ON THE OCR-SPECIFIC DETAILS.

final_response_prompt: |-
  <Internal Thinking>
  {}
  </Internal Thinking>

  <Question>
  {}
  </Question>

  The <Internal Thinking> above represents your detailed OCR analysis and thought process regarding the <Question> about an image. Based on this, generate a rich and high-quality final response that accurately transcribes or describes the text as requested.

  If the <Question> demands a structured transcription (e.g., a form or a label), provide it in a clear, organized format. For general text, provide a coherent block of transcribed text.

  Ensure your response directly and comprehensively answers the <Question> based on your <Internal Thinking> about the OCR process.
