# config.yaml
# Configuration for OCR QRA pipeline

data_path: src/data/salesforce_ocr.json
model_name: google/gemini-2.0-flash-exp:free
api_url: https://openrouter.ai/api/v1
max_search_attempts: 3
max_search_depth: 2
efficient_search: true
num_process: 2
limit_num: null
image_dir: salesforce_images
reports_prompts_path: src/data/reports prompts.json
start_index: 0
batch_size: 50
